name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.18.x ]
    steps:
    - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout
      uses: actions/checkout@v3
    - name: makefile
      run: make
